### PR TITLE
Fix CI failures for new pages (SOFTWARE-4343)

### PR DESCRIPTION
**Pull request by brianhlin**
1.  MkDocs generates new pages with full links to edit the doc in
GitHub and to itself somewhere
2.  Linkchecker dutifully checks that these links return reasonable
HTTP codes, which they won't because they haven't been published yet
in a PR scenario

### CODE REVIEW

**Comment by brianhlin** [comment]
CI failures are due to two bad links (https://github.com/opensciencegrid/research-facilitation/runs/1818823649?check_suite_focus=true#step:5:41) but are otherwise unrelated to this change

**Review by jmvera255 — COMMENTED** [review]
I'm not quite clear on your last comment @brianhlin "CI failures are due to two bad links (https://github.com/opensciencegrid/research-facilitation/runs/1818823649?check_suite_focus=true#step:5:41) but are otherwise unrelated to this change"

So the fix in this PR is neither causing nor fixing the CI build failure? does the failure need to be addressed?

**Comment by brianhlin** [comment]
> So the fix in this PR is neither causing nor fixing the CI build failure? does the failure need to be addressed?

Yup, this PR is solely for fixing an issue the linkchecker has when you add new pages to `mkdocs.yml`. In the case of the current failure, the validation CI is detecting that there are two links that don't resolve so they should probably be fixed. It looks like these are the two lines:

- https://github.com/opensciencegrid/research-facilitation/blame/master/docs/accounts-and-projects/projects.md#L63
- https://github.com/opensciencegrid/research-facilitation/blame/master/docs/accounts-and-projects/accounts.md#L119

**Comment by jmvera255** [comment]
@brianhlin @rynge thoughts on why the validation CI is still failing?

**Comment by brianhlin** [comment]
Hey @jmvera255 I think I've fixed most of the errors. There were some typos in `mkdocs.yml` that resulted in the errors on each page, missing CSS/favicons (that's an oversight of our documentation), and the checker not having access to a google doc. After all that it looks like there's one remaining real link failure: https://github.com/opensciencegrid/research-facilitation/pull/20/checks?check_run_id=1834619514#step:7:10

**Pull request merged**
